_wandb:
    value:
        cli_version: 0.22.1
        e:
            c7fxegnpplr6t21y92nbdoyr8yim17et:
                args:
                    - --agents
                    - "4"
                    - --timesteps
                    - "100000"
                    - --results-dir
                    - multi_agent_racing_results
                    - --wandb
                codePath: metadrive-custom-racing\examples\curriculum_multi_agent_racing.py
                codePathLocal: examples\curriculum_multi_agent_racing.py
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "253615927296"
                        used: "247960727552"
                email: Baldemarguajardo20@gmail.com
                executable: C:\Python313\python.exe
                git:
                    commit: d8f5ff11aabf2d0169a4adcb40e078434cbc235c
                    remote: https://github.com/Joshua-Handy/ApexAI.git
                host: Balde
                memory:
                    total: "17005576192"
                os: Windows-11-10.0.26100-SP0
                program: C:\Users\balde\OneDrive\Documents\SeniorProject\metadrive-custom-racing\examples\curriculum_multi_agent_racing.py
                python: CPython 3.13.1
                root: C:\Users\balde\OneDrive\Documents\SeniorProject\metadrive-custom-racing
                startedAt: "2025-10-22T04:53:27.327303Z"
                writerId: c7fxegnpplr6t21y92nbdoyr8yim17et
        m: []
        python_version: 3.13.1
        t:
            "1":
                - 1
                - 105
            "2":
                - 1
                - 105
            "3":
                - 13
                - 16
            "4": 3.13.1
            "5": 0.22.1
            "8":
                - 3
            "12": 0.22.1
            "13": windows-amd64
algorithm:
    value: PPO_Shared_Policy_Curriculum
curriculum_phases:
    value: 1
done_logic:
    value: per_agent
num_agents:
    value: 4
perception:
    value: lidar
racing_track:
    value: right_turn_oval
total_timesteps:
    value: 100000
