_current_progress_remaining:
    value: 1
_custom_logger:
    value: "False"
_episode_num:
    value: 0
_last_episode_starts:
    value: '[ True]'
_last_obs:
    value: |-
        [[0.00207805 0.00707071 0.00447178 0.00012344 0.00447178 0.00447178
          0.00447178 0.         0.00418596 0.00706964 0.00434592 0.
          0.00447178 0.00447178 0.00691365 0.00284797 0.00554662 0.00707071
          0.00707071 0.00707071 0.00707071 0.00707071 0.00707071 0.00707071
          0.00707071 0.00707071 0.00707071 0.00707071 0.00707071 0.00707071
          0.00707071 0.00707071 0.00707071 0.00707071 0.00707071 0.00707071
          0.00707071 0.00707071 0.00707071 0.00707071 0.00707071 0.00707071
          0.00707071 0.00707071 0.00707071 0.00707071 0.00707071 0.00707071
          0.00707071 0.00707071 0.00707071 0.00707071 0.00707071 0.00707071
          0.00707071 0.00707071 0.00707071 0.00707071 0.00707071 0.00707071
          0.00707071 0.00707071 0.00707071 0.00277293 0.00253768 0.0023537
          0.00230987 0.00707071 0.00707071 0.00707071 0.00707071 0.00707071
          0.00707071 0.00707071 0.00707071 0.00707071 0.00707071 0.00707071
          0.00707071 0.00707071 0.00707071 0.00707071 0.00707071 0.00707071
          0.00707071 0.00707071 0.00707071 0.00707071 0.00707071 0.00707071
          0.00707071]]
_last_original_obs:
    value: |-
        [[0.21246392 1.         0.5        0.01234568 0.5        0.5
          0.5        0.         0.46096674 0.99969685 0.48259124 0.
          0.5        0.5        0.9569945  0.29713047 0.6666667  1.
          1.         1.         1.         1.         1.         1.
          1.         1.         1.         1.         1.         1.
          1.         1.         1.         1.         1.         1.
          1.         1.         1.         1.         1.         1.
          1.         1.         1.         1.         1.         1.
          1.         1.         1.         1.         1.         1.
          1.         1.         1.         1.         1.         1.
          1.         1.         1.         0.2886401  0.26238212 0.24219784
          0.23743066 1.         1.         1.         1.         1.
          1.         1.         1.         1.         1.         1.
          1.         1.         1.         1.         1.         1.
          1.         1.         1.         1.         1.         1.
          1.        ]]
_logger:
    value: <stable_baselines3.common.logger.Logger object at 0x0000022110BD4D70>
_n_updates:
    value: 0
_num_timesteps_at_start:
    value: 0
_stats_window_size:
    value: 100
_total_timesteps:
    value: 600000
_vec_normalize_env:
    value: <stable_baselines3.common.vec_env.vec_normalize.VecNormalize object at 0x0000022106381BE0>
_wandb:
    value:
        cli_version: 0.22.1
        code_path: code/metadrive-custom-racing/examples/train_multi_custom_speedway.py
        e:
            np1gde7r6dfq76off0v3i9msmkjwusfn:
                args:
                    - --agent-names
                    - Alek
                    - Saegan
                    - --timesteps
                    - "600000"
                    - --vecnorm
                    - --wandb
                codePath: metadrive-custom-racing\examples\train_multi_custom_speedway.py
                codePathLocal: examples\train_multi_custom_speedway.py
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "253615927296"
                        used: "251685875712"
                email: Baldemarguajardo20@gmail.com
                executable: C:\Python313\python.exe
                git:
                    commit: 6839efd2f76a04c6dd96256cef4e1059dc20b502
                    remote: https://github.com/Joshua-Handy/ApexAI.git
                host: Balde
                memory:
                    total: "17005576192"
                os: Windows-11-10.0.26100-SP0
                program: C:\Users\balde\OneDrive\Documents\SeniorProject\metadrive-custom-racing\examples\train_multi_custom_speedway.py
                python: CPython 3.13.1
                root: C:\Users\balde\OneDrive\Documents\SeniorProject\metadrive-custom-racing
                startedAt: "2025-11-22T02:56:00.825546Z"
                writerId: np1gde7r6dfq76off0v3i9msmkjwusfn
        m: []
        python_version: 3.13.1
        t:
            "1":
                - 1
                - 105
            "2":
                - 1
                - 105
            "3":
                - 1
                - 2
                - 13
                - 16
                - 22
                - 35
            "4": 3.13.1
            "5": 0.22.1
            "8":
                - 3
            "12": 0.22.1
            "13": windows-amd64
action_noise:
    value: None
action_space:
    value: Box(-1.0, 1.0, (2,), float32)
agent_id:
    value: 0
agent_name:
    value: Alek
algo:
    value: PPO
algorithm:
    value: PPO
batch_size:
    value: 256
clip_range:
    value: 0.2
clip_range_vf:
    value: None
device:
    value: cpu
ent_coef:
    value: 0.01
env:
    value: <stable_baselines3.common.vec_env.vec_normalize.VecNormalize object at 0x0000022106381BE0>
ep_info_buffer:
    value: deque([], maxlen=100)
ep_success_buffer:
    value: deque([], maxlen=100)
gae_lambda:
    value: 0.95
gamma:
    value: 0.99
learning_rate:
    value: 0.0003
lr_schedule:
    value: FloatSchedule(ConstantSchedule(val=0.0003))
max_grad_norm:
    value: 0.5
n_envs:
    value: 1
n_epochs:
    value: 15
n_steps:
    value: 4096
normalize_advantage:
    value: "True"
num_timesteps:
    value: 0
observation_space:
    value: Box(-0.0, 1.0, (91,), float32)
policy:
    value: |-
        ActorCriticPolicy(
          (features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (pi_features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (vf_features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (mlp_extractor): MlpExtractor(
            (policy_net): Sequential(
              (0): Linear(in_features=91, out_features=256, bias=True)
              (1): ReLU()
              (2): Linear(in_features=256, out_features=256, bias=True)
              (3): ReLU()
              (4): Linear(in_features=256, out_features=128, bias=True)
              (5): ReLU()
            )
            (value_net): Sequential(
              (0): Linear(in_features=91, out_features=256, bias=True)
              (1): ReLU()
              (2): Linear(in_features=256, out_features=256, bias=True)
              (3): ReLU()
              (4): Linear(in_features=256, out_features=128, bias=True)
              (5): ReLU()
            )
          )
          (action_net): Linear(in_features=128, out_features=2, bias=True)
          (value_net): Linear(in_features=128, out_features=1, bias=True)
        )
policy_class:
    value: <class 'stable_baselines3.common.policies.ActorCriticPolicy'>
policy_kwargs:
    value: '{''net_arch'': [256, 256, 128], ''activation_fn'': <class ''torch.nn.modules.activation.ReLU''>, ''ortho_init'': True}'
rollout_buffer:
    value: <stable_baselines3.common.buffers.RolloutBuffer object at 0x00000221063823C0>
rollout_buffer_class:
    value: <class 'stable_baselines3.common.buffers.RolloutBuffer'>
rollout_buffer_kwargs:
    value: '{}'
sde_sample_freq:
    value: -1
seed:
    value: 0
start_time:
    value: 1763780168403079300
target_kl:
    value: 0.01
tensorboard_log:
    value: C:\Users\balde\OneDrive\Documents\SeniorProject\metadrive-custom-racing\examples\..\results\results_agent_Alek\tensorboard
timesteps:
    value: 600000
track:
    value: custom_speedway
use_sde:
    value: "False"
vecnorm:
    value: true
verbose:
    value: 1
vf_coef:
    value: 0.5
