_current_progress_remaining:
    value: 0.0005760000000000209
_custom_logger:
    value: "False"
_episode_num:
    value: 0
_last_episode_starts:
    value: '[ True]'
_last_obs:
    value: |-
        [[0.5555556  0.5555556  0.5        0.01234568 0.5        0.5
          0.5        0.         0.5        0.55       0.5        0.
          0.5        0.5        0.75       0.5        0.         0.5
          0.5        1.         1.         1.         1.         1.
          1.         1.         1.         1.         1.         1.
          1.         1.         1.         1.         1.         1.
          1.         1.         1.         1.         1.         1.
          1.         1.         1.         1.         1.         1.
          1.         1.         1.         1.         1.         1.
          1.         1.         1.         1.         1.         1.
          1.         1.         1.         1.         1.         1.
          1.         1.         1.         1.         1.         1.
          1.         1.         1.         1.         1.         1.
          1.         1.         1.         1.         1.         1.
          1.         1.         1.         1.         1.         1.
          1.         1.         1.         1.         1.         1.
          1.         1.         1.         1.         1.         1.
          1.         1.         1.         1.         1.         1.
          1.         1.         1.         1.         1.         1.
          1.         1.         1.         1.         1.         1.
          1.         1.         1.         1.         1.         1.
          1.         1.         1.         1.         1.         1.
          1.         1.         1.         1.         1.         1.
          1.         1.         1.         1.         1.         1.
          1.         1.         1.         1.         1.         1.
          1.         1.         1.         1.         1.         1.
          1.         1.         1.         1.         1.         1.
          1.         1.         1.         1.         1.         1.
          1.         1.         1.         1.         1.         1.
          1.         1.         1.         1.         1.         1.
          1.         1.         1.         1.         1.         1.
          1.         1.         1.         1.         1.         1.
          1.         1.         1.         1.         1.         1.
          1.         1.         1.         1.         1.         1.
          1.         1.         1.         1.         1.         1.
          1.         1.         1.         1.         1.         1.
          1.         1.         1.         1.         1.         1.
          1.         1.         1.         1.         1.         1.
          1.         1.         1.         1.         1.         1.
          1.         1.         1.         1.         1.         1.
          1.         1.         1.         1.         1.         1.
          1.         1.         1.         1.         1.         1.
          1.         1.         1.         1.         1.         1.
          1.        ]]
_last_original_obs:
    value: None
_logger:
    value: <stable_baselines3.common.logger.Logger object at 0x000001CE10F301A0>
_n_updates:
    value: 336
_num_timesteps_at_start:
    value: 500000
_stats_window_size:
    value: 100
_total_timesteps:
    value: 700000
_vec_normalize_env:
    value: None
_wandb:
    value:
        cli_version: 0.22.1
        code_path: code/metadrive-custom-racing/examples/train_sb3.py
        e:
            w484bb557t11fc26ypqnzoxzw994gbcb:
                args:
                    - --track
                    - right_oval
                    - --timesteps
                    - "200000"
                    - --personality
                    - cautious_speedster
                    - --resume-from
                    - examples/results_agent_0/checkpoint_right_oval_500000_steps.zip
                    - --results-dir
                    - examples/results_agent_0
                    - --checkpoint-freq
                    - "10000"
                    - --learning-rate
                    - "5e-6"
                    - --batch-size
                    - "64"
                    - --n-steps
                    - "1024"
                    - --gamma
                    - "0.995"
                    - --gae-lambda
                    - "0.98"
                    - --clip-range
                    - "0.05"
                    - --wandb
                    - --wandb-project
                    - metadrive-racing-continued
                    - --wandb-name
                    - Careful_Carl_CRASH_FIX_TRAINING
                    - --no-eval
                codePath: metadrive-custom-racing\examples\train_sb3.py
                codePathLocal: examples\train_sb3.py
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "253615927296"
                        used: "246323609600"
                email: Baldemarguajardo20@gmail.com
                executable: C:\Python313\python.exe
                git:
                    commit: daebfe8509d3e35876a686714ec1093bfa985ba6
                    remote: https://github.com/Joshua-Handy/ApexAI.git
                host: Balde
                memory:
                    total: "17005576192"
                os: Windows-11-10.0.26100-SP0
                program: C:\Users\balde\OneDrive\Documents\SeniorProject\metadrive-custom-racing\examples\train_sb3.py
                python: CPython 3.13.1
                root: C:\Users\balde\OneDrive\Documents\SeniorProject\metadrive-custom-racing
                startedAt: "2025-10-09T18:38:23.967745Z"
                writerId: w484bb557t11fc26ypqnzoxzw994gbcb
        m: []
        python_version: 3.13.1
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 1
                - 13
                - 16
                - 22
                - 35
                - 61
            "4": 3.13.1
            "5": 0.22.1
            "8":
                - 3
            "12": 0.22.1
            "13": windows-amd64
action_noise:
    value: None
action_space:
    value: Box(-1.0, 1.0, (2,), float32)
algo:
    value: PPO
algorithm:
    value: PPO
batch_size:
    value: 64
checkpoint_freq:
    value: 10000
clip_range:
    value: 0.05
clip_range_vf:
    value: None
device:
    value: cpu
ent_coef:
    value: 0.01
env:
    value: <stable_baselines3.common.vec_env.dummy_vec_env.DummyVecEnv object at 0x000001CE032E6BA0>
ep_info_buffer:
    value: 'deque([{''r'': 24.835241, ''l'': 54, ''t'': 4485.466474}, {''r'': 26.167288, ''l'': 60, ''t'': 4485.7837}, {''r'': 72.701664, ''l'': 114, ''t'': 4486.257475}, {''r'': 32.890963, ''l'': 61, ''t'': 4486.581239}, {''r'': 37.045262, ''l'': 80, ''t'': 4486.97462}, {''r'': 57.665004, ''l'': 102, ''t'': 4487.489975}, {''r'': 23.992983, ''l'': 52, ''t'': 4487.803136}, {''r'': 114.337382, ''l'': 204, ''t'': 4488.583043}, {''r'': 29.055285, ''l'': 58, ''t'': 4488.897396}, {''r'': 19.822313, ''l'': 46, ''t'': 4489.19123}, {''r'': 70.438405, ''l'': 127, ''t'': 4489.716757}, {''r'': 38.807814, ''l'': 69, ''t'': 4490.109674}, {''r'': 32.422368, ''l'': 63, ''t'': 4490.579334}, {''r'': 22.4437, ''l'': 53, ''t'': 4490.94618}, {''r'': 26.327352, ''l'': 61, ''t'': 4491.352621}, {''r'': 20.62134, ''l'': 51, ''t'': 4491.699887}, {''r'': 37.820126, ''l'': 82, ''t'': 4492.190835}, {''r'': 31.180875, ''l'': 67, ''t'': 4492.549433}, {''r'': 25.469664, ''l'': 59, ''t'': 4492.887871}, {''r'': 34.264297, ''l'': 71, ''t'': 4493.27536}, {''r'': 17.126063, ''l'': 48, ''t'': 4493.57559}, {''r'': 34.130604, ''l'': 70, ''t'': 4493.946974}, {''r'': 22.871157, ''l'': 49, ''t'': 4494.249235}, {''r'': 28.58214, ''l'': 63, ''t'': 4494.585856}, {''r'': 27.002668, ''l'': 56, ''t'': 4494.910437}, {''r'': 15.930765, ''l'': 44, ''t'': 4495.202722}, {''r'': 27.401108, ''l'': 57, ''t'': 4495.513707}, {''r'': 37.355569, ''l'': 72, ''t'': 4496.00171}, {''r'': 47.609073, ''l'': 91, ''t'': 4496.440211}, {''r'': 47.334047, ''l'': 92, ''t'': 4496.870968}, {''r'': 22.917386, ''l'': 54, ''t'': 4497.215195}, {''r'': 28.699442, ''l'': 57, ''t'': 4497.540567}, {''r'': 64.767488, ''l'': 117, ''t'': 4498.061646}, {''r'': 25.736109, ''l'': 53, ''t'': 4498.409522}, {''r'': 37.838828, ''l'': 71, ''t'': 4498.815534}, {''r'': 84.892372, ''l'': 136, ''t'': 4499.389391}, {''r'': 29.850857, ''l'': 67, ''t'': 4499.726677}, {''r'': 28.18086, ''l'': 63, ''t'': 4500.120911}, {''r'': 55.996686, ''l'': 109, ''t'': 4500.661322}, {''r'': 38.797889, ''l'': 73, ''t'': 4501.094427}, {''r'': 31.743577, ''l'': 66, ''t'': 4501.542572}, {''r'': 69.963188, ''l'': 106, ''t'': 4502.044527}, {''r'': 36.088667, ''l'': 76, ''t'': 4502.459068}, {''r'': 30.492902, ''l'': 61, ''t'': 4502.782569}, {''r'': 49.840237, ''l'': 96, ''t'': 4503.225846}, {''r'': 24.549285, ''l'': 54, ''t'': 4503.522046}, {''r'': 16.629089, ''l'': 39, ''t'': 4503.815531}, {''r'': 71.897978, ''l'': 130, ''t'': 4504.445623}, {''r'': 81.956804, ''l'': 135, ''t'': 4505.013093}, {''r'': 139.492013, ''l'': 198, ''t'': 4505.802814}, {''r'': 42.014136, ''l'': 84, ''t'': 4506.420713}, {''r'': 273.943301, ''l'': 371, ''t'': 4508.320894}, {''r'': 56.869882, ''l'': 113, ''t'': 4508.950647}, {''r'': 62.809933, ''l'': 103, ''t'': 4509.55371}, {''r'': 127.849098, ''l'': 178, ''t'': 4510.27931}, {''r'': 25.153851, ''l'': 56, ''t'': 4510.690534}, {''r'': 37.597062, ''l'': 82, ''t'': 4511.228349}, {''r'': 36.255188, ''l'': 71, ''t'': 4511.666005}, {''r'': 46.52582, ''l'': 88, ''t'': 4512.167691}, {''r'': 49.120422, ''l'': 90, ''t'': 4512.592164}, {''r'': 139.462154, ''l'': 224, ''t'': 4513.417861}, {''r'': 131.762878, ''l'': 194, ''t'': 4514.176884}, {''r'': 73.74409, ''l'': 126, ''t'': 4514.740099}, {''r'': 73.13083, ''l'': 123, ''t'': 4515.302273}, {''r'': 53.718316, ''l'': 93, ''t'': 4515.787512}, {''r'': 33.068649, ''l'': 64, ''t'': 4516.168864}, {''r'': 103.219246, ''l'': 196, ''t'': 4517.075737}, {''r'': 88.818414, ''l'': 141, ''t'': 4517.765902}, {''r'': 24.067741, ''l'': 54, ''t'': 4518.210011}, {''r'': 157.359704, ''l'': 231, ''t'': 4519.155606}, {''r'': 43.214627, ''l'': 87, ''t'': 4519.552821}, {''r'': 41.584909, ''l'': 87, ''t'': 4520.050254}, {''r'': 75.564003, ''l'': 149, ''t'': 4520.692459}, {''r'': 212.014587, ''l'': 293, ''t'': 4521.683789}, {''r'': 126.219688, ''l'': 187, ''t'': 4522.421235}, {''r'': 62.306533, ''l'': 114, ''t'': 4522.952827}, {''r'': 37.729076, ''l'': 67, ''t'': 4523.394172}, {''r'': 41.223702, ''l'': 78, ''t'': 4523.81373}, {''r'': 57.009276, ''l'': 112, ''t'': 4524.359918}, {''r'': 62.492856, ''l'': 110, ''t'': 4525.008111}, {''r'': 49.134525, ''l'': 100, ''t'': 4525.503283}, {''r'': 71.805568, ''l'': 122, ''t'': 4526.167477}, {''r'': 68.517977, ''l'': 105, ''t'': 4526.727166}, {''r'': 30.438502, ''l'': 64, ''t'': 4527.367356}, {''r'': 111.499518, ''l'': 165, ''t'': 4528.218173}, {''r'': 87.31269, ''l'': 134, ''t'': 4528.854776}, {''r'': 143.288466, ''l'': 208, ''t'': 4529.727843}, {''r'': 121.65739, ''l'': 167, ''t'': 4530.512661}, {''r'': 70.061011, ''l'': 122, ''t'': 4531.152384}, {''r'': 137.986698, ''l'': 239, ''t'': 4532.07313}, {''r'': 33.459739, ''l'': 75, ''t'': 4532.48681}, {''r'': 123.910226, ''l'': 204, ''t'': 4533.244034}, {''r'': 178.734713, ''l'': 245, ''t'': 4534.209585}, {''r'': 48.444347, ''l'': 87, ''t'': 4534.661215}, {''r'': 44.279134, ''l'': 87, ''t'': 4535.0618}, {''r'': 72.213866, ''l'': 113, ''t'': 4535.57915}, {''r'': 57.658172, ''l'': 105, ''t'': 4536.248815}, {''r'': 41.117796, ''l'': 71, ''t'': 4536.613099}, {''r'': 20.127614, ''l'': 47, ''t'': 4536.943928}, {''r'': 21.036251, ''l'': 57, ''t'': 4537.28552}], maxlen=100)'
ep_success_buffer:
    value: deque([], maxlen=100)
eval_freq:
    value: 5000
gae_lambda:
    value: 0.98
gamma:
    value: 0.995
learning_rate:
    value: 5e-06
lr_schedule:
    value: FloatSchedule(ConstantSchedule(val=0.0003))
max_grad_norm:
    value: 0.5
n_envs:
    value: 1
n_epochs:
    value: 15
n_steps:
    value: 1024
normalize_advantage:
    value: "True"
num_envs:
    value: 1
num_timesteps:
    value: 500000
observation_space:
    value: Box(-0.0, 1.0, (259,), float32)
policy:
    value: |-
        ActorCriticPolicy(
          (features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (pi_features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (vf_features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (mlp_extractor): MlpExtractor(
            (policy_net): Sequential(
              (0): Linear(in_features=259, out_features=256, bias=True)
              (1): ReLU()
              (2): Linear(in_features=256, out_features=256, bias=True)
              (3): ReLU()
              (4): Linear(in_features=256, out_features=128, bias=True)
              (5): ReLU()
            )
            (value_net): Sequential(
              (0): Linear(in_features=259, out_features=256, bias=True)
              (1): ReLU()
              (2): Linear(in_features=256, out_features=256, bias=True)
              (3): ReLU()
              (4): Linear(in_features=256, out_features=128, bias=True)
              (5): ReLU()
            )
          )
          (action_net): Linear(in_features=128, out_features=2, bias=True)
          (value_net): Linear(in_features=128, out_features=1, bias=True)
        )
policy_class:
    value: <class 'stable_baselines3.common.policies.ActorCriticPolicy'>
policy_kwargs:
    value: '{''net_arch'': [256, 256, 128], ''activation_fn'': <class ''torch.nn.modules.activation.ReLU''>, ''ortho_init'': True}'
rollout_buffer:
    value: <stable_baselines3.common.buffers.RolloutBuffer object at 0x000001CE06FDFA10>
rollout_buffer_class:
    value: <class 'stable_baselines3.common.buffers.RolloutBuffer'>
rollout_buffer_kwargs:
    value: '{}'
sde_sample_freq:
    value: -1
seed:
    value: 0
start_time:
    value: 1760035109239117200
target_kl:
    value: 0.01
tensorboard_log:
    value: results_agent_0\tensorboard
timesteps:
    value: 200000
track:
    value: right_oval
use_sde:
    value: "False"
vecnorm:
    value: false
verbose:
    value: 1
vf_coef:
    value: 0.5
