_current_progress_remaining:
    value: 1
_custom_logger:
    value: "False"
_episode_num:
    value: 0
_last_episode_starts:
    value: '[ True]'
_last_obs:
    value: |-
        [[0.84416336 0.8225033  0.5        0.01234568 0.5        0.5
          0.5        0.         0.54332006 0.5869644  0.5019494  0.
          0.5        0.5        0.86596936 0.15931477 1.         1.
          0.8333333  0.17720993 0.17788668 1.         1.         1.
          1.         1.         1.         1.         1.         1.
          1.         1.         1.         1.         1.         1.
          1.         1.         1.         1.         1.         1.
          1.         1.         1.         1.         1.         1.
          1.         1.         1.         1.         1.         0.11513694
          0.11382096 0.11338782 0.11382098 1.         1.         1.
          1.         1.         1.         1.         1.         1.
          1.         1.         1.         1.         1.         1.
          1.         1.         1.         1.         1.         1.
          1.         1.         1.         1.         1.         1.
          1.         1.         1.         1.         1.         1.
          0.17788687]]
_last_original_obs:
    value: None
_logger:
    value: <stable_baselines3.common.logger.Logger object at 0x000001B2146BDBE0>
_n_updates:
    value: 0
_num_timesteps_at_start:
    value: 0
_stats_window_size:
    value: 100
_total_timesteps:
    value: 25000
_vec_normalize_env:
    value: None
_wandb:
    value:
        cli_version: 0.22.1
        e:
            e64dx5m3uztjd3r3ugzemqe4mhshfzl6:
                args:
                    - --agents
                    - "4"
                    - --timesteps
                    - "1500000"
                    - --track
                    - right_oval
                    - --results-dir
                    - coordinated_4agent_curve_learning_v5
                    - --wandb
                codePath: metadrive-custom-racing\examples\train_coordinated_multi_agent.py
                codePathLocal: train_coordinated_multi_agent.py
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "253615927296"
                        used: "249593716736"
                email: Baldemarguajardo20@gmail.com
                executable: C:\Python313\python.exe
                git:
                    commit: daebfe8509d3e35876a686714ec1093bfa985ba6
                    remote: https://github.com/Joshua-Handy/ApexAI.git
                host: Balde
                memory:
                    total: "17005576192"
                os: Windows-11-10.0.26100-SP0
                program: C:\Users\balde\OneDrive\Documents\SeniorProject\metadrive-custom-racing\examples\train_coordinated_multi_agent.py
                python: CPython 3.13.1
                root: C:\Users\balde\OneDrive\Documents\SeniorProject\metadrive-custom-racing\examples
                startedAt: "2025-10-14T17:36:33.004781Z"
                writerId: e64dx5m3uztjd3r3ugzemqe4mhshfzl6
        m: []
        python_version: 3.13.1
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 1
                - 13
                - 16
                - 22
                - 61
            "4": 3.13.1
            "5": 0.22.1
            "8":
                - 3
            "12": 0.22.1
            "13": windows-amd64
action_noise:
    value: None
action_space:
    value: Box(-1.0, 1.0, (2,), float32)
algo:
    value: PPO
algorithm:
    value: Coordinated PPO Curve-Learning
batch_size:
    value: 64
clip_range:
    value: FloatSchedule(ConstantSchedule(val=0.1))
clip_range_vf:
    value: None
crash_termination:
    value: false
device:
    value: cpu
driving_reward:
    value: 5
ent_coef:
    value: 0.01
env:
    value: <stable_baselines3.common.vec_env.dummy_vec_env.DummyVecEnv object at 0x000001B208AC0C20>
ep_info_buffer:
    value: deque([], maxlen=100)
ep_success_buffer:
    value: deque([], maxlen=100)
focus:
    value: CURVE_NAVIGATION_LEARNING
gae_lambda:
    value: 0.95
gamma:
    value: 0.995
learning_rate:
    value: 5e-06
lr_schedule:
    value: FloatSchedule(ConstantSchedule(val=5e-06))
max_grad_norm:
    value: 0.5
n_envs:
    value: 1
n_epochs:
    value: 10
n_steps:
    value: 1024
normalize_advantage:
    value: "True"
num_agents:
    value: 4
num_timesteps:
    value: 0
observation_space:
    value: Box(-0.0, 1.0, (91,), float32)
policy:
    value: |-
        ActorCriticPolicy(
          (features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (pi_features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (vf_features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (mlp_extractor): MlpExtractor(
            (policy_net): Sequential(
              (0): Linear(in_features=91, out_features=64, bias=True)
              (1): Tanh()
              (2): Linear(in_features=64, out_features=64, bias=True)
              (3): Tanh()
            )
            (value_net): Sequential(
              (0): Linear(in_features=91, out_features=64, bias=True)
              (1): Tanh()
              (2): Linear(in_features=64, out_features=64, bias=True)
              (3): Tanh()
            )
          )
          (action_net): Linear(in_features=64, out_features=2, bias=True)
          (value_net): Linear(in_features=64, out_features=1, bias=True)
        )
policy_class:
    value: <class 'stable_baselines3.common.policies.ActorCriticPolicy'>
policy_kwargs:
    value: '{}'
rollout_buffer:
    value: <stable_baselines3.common.buffers.RolloutBuffer object at 0x000001B208AC1010>
rollout_buffer_class:
    value: <class 'stable_baselines3.common.buffers.RolloutBuffer'>
rollout_buffer_kwargs:
    value: '{}'
sde_sample_freq:
    value: -1
seed:
    value: None
sensors_enabled:
    value: true
speed_reward:
    value: 2
start_time:
    value: 1760463405639737400
success_reward:
    value: 30
target_kl:
    value: None
tensorboard_log:
    value: coordinated_4agent_curve_learning_v5\tensorboard_agent0
timesteps:
    value: 1500000
track:
    value: right_oval
use_lateral_reward:
    value: true
use_sde:
    value: "False"
verbose:
    value: 1
vf_coef:
    value: 0.5
